SELECT * FROM SALES
SELECT * FROM CUSTOMERS

SELECT * FROM CITY
SELECT * FROM PRODUCTS



-- QUESTION 1 : Coffee Consumers Count
-- How many people in each city are estimated to consume coffee, given that 25% of the population does?

SELECT 
CITY.CITY_NAME,
CITY.POPULATION ,
ROUND(CITY.POPULATION * 0.25 / 100000,2) AS COFFEE_CONSUMERS_IN_LAKHS
FROM SALES
JOIN 
CUSTOMERS
ON CUSTOMERS.CUSTOMER_ID = SALES.CUSTOMER_ID
JOIN CITY
ON CITY.CITY_ID = CUSTOMERS.CITY_ID
GROUP BY 1,2
ORDER BY COFFEE_CONSUMERS_IN_LAKHS DESC




-- QUESTION 2 : Total Revenue from Coffee Sales
-- What is the total revenue generated from coffee sales across all cities in the last quarter of 2023?

with ct
as 
(
	SELECT CITY.CITY_NAME,
	SUM(SALES.TOTAL) AS TOTAL_REVENUE,
	EXTRACT (QUARTER FROM SALES.SALE_DATE) AS QUARTER_NUMBER,
	EXTRACT (YEAR FROM SALES.SALE_DATE) AS YEAR
	FROM SALES
	JOIN CUSTOMERS
	ON CUSTOMERS.CUSTOMER_ID = SALES.CUSTOMER_ID
	JOIN CITY 
	ON CITY.CITY_ID = CUSTOMERS.CITY_ID
	GROUP BY 1 , 3 ,4
	ORDER BY 4 , 3
)
select * 
from ct
where QUARTER_NUMBER = 4
AND YEAR = 2023




-- QUESTION 3 : Sales Count for Each Product
-- How many units of each coffee product have been sold:

SELECT PRODUCTS.PRODUCT_NAME ,
COUNT(SALES.SALE_ID) AS SALES_COUNT
FROM SALES
JOIN 
PRODUCTS
ON SALES.PRODUCT_ID = PRODUCTS.PRODUCT_ID 
GROUP BY 1
ORDER BY 2 DESC


-- QUESTION 4 : Average Sales Amount per City

SELECT CITY.CITY_NAME,
ROUND(AVG(SALES.TOTAL) ::NUMERIC,2) AS AVG_SALES_AMOUNT_PER_CITY
FROM SALES 
LEFT JOIN CUSTOMERS
ON CUSTOMERS.CUSTOMER_ID =SALES.CUSTOMER_ID
RIGHT JOIN CITY
ON CITY.CITY_ID = CUSTOMERS.CITY_ID
GROUP BY 1
ORDER BY 2 DESC



--QUESTION 5 : What is the average sales amount per customer in each city?

SELECT CITY.CITY_NAME,
ROUND(
	  SUM(SALES.TOTAL) ::NUMERIC /
							    COUNT(DISTINCT CUSTOMERS.CUSTOMER_ID) ::NUMERIC ,2
	  ) AS AVG_SALES_AMOUNT_PER_CUSTOMER
FROM SALES 
JOIN CUSTOMERS
ON SALES.CUSTOMER_ID = CUSTOMERS.CUSTOMER_ID 
JOIN 
CITY
ON CITY.CITY_ID = CUSTOMERS.CITY_ID
GROUP BY 1
ORDER BY 2 DESC



-- QUESTION 6 : City Population and Coffee Consumers**  
-- Provide a list of cities along with their populations and estimated coffee consumers {25% OF POPULATION}


SELECT 
CITY_NAME ,
POPULATION,
ROUND((POPULATION * 0.25 / 100000),2) AS ESTIMATED_COFFE_CONSUMERS_IN_LAKHS
FROM
CITY


--QUESTION 7 : Top Selling Products by City**  
-- What are the top 3 selling products in each city based on sales volume?

WITH CT
AS 
(
SELECT
CITY.CITY_NAME,
PRODUCTS.PRODUCT_NAME,
COUNT(PRODUCTS.PRODUCT_ID) AS PRODUCT_COUNT,
ROW_NUMBER() OVER (PARTITION BY CITY.CITY_NAME ORDER BY COUNT(PRODUCTS.PRODUCT_ID)DESC) AS RANK
FROM
SALES 
JOIN CUSTOMERS
ON SALES.CUSTOMER_ID = CUSTOMERS.CUSTOMER_ID 
JOIN CITY
ON CITY.CITY_ID = CUSTOMERS.CITY_ID
JOIN PRODUCTS
ON 
PRODUCTS.PRODUCT_ID = SALES.PRODUCT_ID
GROUP BY 1,2
)
SELECT * 
FROM CT
WHERE RANK < 4


 
--QUESTION 8: Customer Segmentation by City
-- How many unique customers are there in each city who have purchased coffee products?


SELECT CITY.CITY_NAME , COUNT(DISTINCT CUSTOMERS.CUSTOMER_ID)  FROM SALES
JOIN CUSTOMERS
ON SALES.CUSTOMER_ID = CUSTOMERS.CUSTOMER_ID 
JOIN PRODUCTS 
ON PRODUCTS.PRODUCT_ID = SALES.PRODUCT_ID
JOIN CITY 
ON CITY.CITY_ID = CUSTOMERS.CITY_ID
WHERE PRODUCTS.PRODUCT_ID < 15 GROUP BY 1



-- QUESTION 9 : Find each city and their average sale per customer and avg rent per customer


SELECT 
CITY.CITY_NAME , 
CITY.ESTIMATED_RENT ,
ROUND(
		SUM(SALES.TOTAL) ::NUMERIC / COUNT(DISTINCT SALES.CUSTOMER_ID) ::NUMERIC ,2
     ) AS AVG_SALES_AMOUNT_PER_CUSTOMER,
 ROUND(
		CITY.ESTIMATED_RENT ::NUMERIC / COUNT(DISTINCT SALES.CUSTOMER_ID)::NUMERIC,2
	 ) AS AVG_ESTIMATED_RENT 
FROM SALES
JOIN 
CUSTOMERS
ON SALES.CUSTOMER_ID = CUSTOMERS.CUSTOMER_ID 
JOIN 
PRODUCTS 
ON PRODUCTS.PRODUCT_ID = SALES.PRODUCT_ID
JOIN 
CITY 
ON CITY.CITY_ID = CUSTOMERS.CITY_ID
GROUP BY 1,2


 --QUESTION 10 : Sales growth rate: Calculate the percentage growth (or decline) in sales over different time periods (monthly) BY EACH CITY


WITH LAST_MONTH_SALES
AS 
(
SELECT 
CITY.CITY_NAME ,
EXTRACT(MONTH FROM SALES.SALE_DATE) AS MONTH, 
EXTRACT(YEAR FROM SALES.SALE_DATE) AS YEAR, 
SUM(SALES.TOTAL) AS CURRENT_MONTH_SALES
FROM 
SALES
JOIN CUSTOMERS
ON SALES.CUSTOMER_ID = CUSTOMERS.CUSTOMER_ID 
JOIN
PRODUCTS 
ON PRODUCTS.PRODUCT_ID = SALES.PRODUCT_ID
JOIN
CITY 
ON CITY.CITY_ID = CUSTOMERS.CITY_ID
GROUP BY 1,2 ,3
ORDER BY 1,3 ,2
),

CT AS
(
SELECT 
CITY_NAME,
MONTH,
YEAR,
CURRENT_MONTH_SALES,
LAG(CURRENT_MONTH_SALES,1) OVER (PARTITION BY CITY_NAME) AS PREVIOUS_MONTH_SALES
FROM LAST_MONTH_SALES
)

SELECT 
CITY_NAME,
MONTH,
YEAR,
CURRENT_MONTH_SALES,
PREVIOUS_MONTH_SALES ,
ROUND((CURRENT_MONTH_SALES - PREVIOUS_MONTH_SALES) ::NUMERIC / PREVIOUS_MONTH_SALES ::NUMERIC*100,2)  AS GROWTH_RATE
FROM CT 
WHERE PREVIOUS_MONTH_SALES IS NOT NULL



--QUESTION 11 : Identify top 3 city based on highest sales, return city name,
-- total sale, total rent, total customers, estimated  coffee consumer


WITH CT
AS
(
SELECT
	CITY.CITY_NAME , 
	SUM(SALES.TOTAL) AS TOTAL_SALES,
	COUNT(SALES.SALE_ID) AS SALES_COUNT,
	CITY.ESTIMATED_RENT,
	COUNT(DISTINCT SALES.CUSTOMER_ID) AS CUSTOMER_COUNT,
	CITY.POPULATION AS TOTAL_POPULATION,
	ROUND(SUM(SALES.TOTAL) ::NUMERIC/ COUNT(DISTINCT SALES.CUSTOMER_ID)::NUMERIC,2) AS AVG_SALES_PER_CUSTOMER,
	ROUND(CITY.ESTIMATED_RENT ::NUMERIC / COUNT(DISTINCT SALES.CUSTOMER_ID)::NUMERIC,2) AS AVG_RENT_PER_CUSTOMER
FROM SALES
JOIN CUSTOMERS
ON SALES.CUSTOMER_ID = CUSTOMERS.CUSTOMER_ID 
JOIN PRODUCTS 
ON PRODUCTS.PRODUCT_ID = SALES.PRODUCT_ID
JOIN CITY 
ON CITY.CITY_ID = CUSTOMERS.CITY_ID
GROUP BY 1,4,6
)
SELECT 
	CITY_NAME,
	TOTAL_SALES,
	SALES_COUNT,
	ESTIMATED_RENT,
	CUSTOMER_COUNT,
	ROUND((TOTAL_POPULATION * 0.25)/1000000,2) AS ESTIMATED_COFFEE_CONSUMERS_IN_MILLIONS,
	AVG_SALES_PER_CUSTOMER,
	AVG_RENT_PER_CUSTOMER
FROM CT 
ORDER BY TOTAL_SALES DESC

-- RECOMMENDATIONS

-- AFTER SEEING THE DATA I WOULD RECOMMEND THAT ( PUNE AND CHENNAI ) ARE GOOD TO GO AND 
-- THE ( BENGALURU )  AT THE THIRD PLACE HAVE VERY HIGH AVG_RENT_PER_CUSTOMERS 
-- THATS WHY I WOULD RECOMMEND THE NEXT CITY ( JAIPUR ) AS THE THIRD CITY WHERE WE CAN 
-- OPEN OUR THIRD COFFE OUTLET


-- CITY 1 : PUNE
-- AVG_RENT_PER_CUSTOMERS = 294.23 WHICH IS VERY LOW
-- AVG_SALES_PER_CUSTOMER = 24197 WHICH IS VERY HIGH
-- TOTAL REVENUE = 1258290 WHICH IS VERY HIGH


-- CITY 2 : CHENNAI 
-- AVG_RENT_PER_CUSTOMERS = 407.14 WHICH IS VERY LOW
-- AVG_SALES_PER_CUSTOMER = 22479.05 WHICH IS VERY HIGH
-- TOTAL REVENUE = 944120 WHICH IS VERY HIGH


-- CITY 3 : JAIPUR
-- AVG_RENT_PER_CUSTOMERS = 156.52 WHICH IS VERY LOW
-- AVG_SALES_PER_CUSTOMER = 11644.20 WHICH IS HIGH
-- TOTAL REVENUE = 803450 WHICH IS VERY HIGH
